=== acastineiraduran/LMXI/tri2/Tema4_esquemasXML/boletines/repasoEsquemas.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--a
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="articulo">
    <xs:complexType>
      <xs:attribute name="codigo" type="xs:string" default="false"/>
    </xs:complexType>
  </xs:element>
</xs:schema>
-->

<!--b
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="empleado">
    <xs:complexType>
      <xs:sequence>
        	<xs:element name="nombre" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
        	<xs:element name="apellidos">
        	  <xs:complexType>
              <xs:sequence>
              <xs:element name="apellido1" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
              <xs:element name="apellido2" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
              
              </xs:sequence>
            </xs:complexType>
        	</xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>
-->

<!-- c
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="documento">
    <xs:complexType mixed="true">
      <xs:sequence>
        <xs:element name="nombre" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
        <xs:element name="fecha" type="xs:date" minOccurs="0" maxOccurs="unbounded"/>
        <xs:element name="hora" type="xs:time" minOccurs="0" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>
-->
<!-- d
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="encargados">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="encargado" minOccurs="0" maxOccurs="unbounded">
          
          <xs:complexType>
            <xs:sequence>
              <xs:element name="nombre" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
              <xs:element name="apellidos" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
      <xs:attribute name="clase" type="xs:string" default="false"/>
    </xs:complexType>
  </xs:element>
</xs:schema>
-->
<!--
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="encargados">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="encargado" minOccurs="0" maxOccurs="unbounded">
          
          <xs:complexType>
           <xs:sequence>
              <xs:element name="nombre" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
              <xs:element name="apellidos" minOccurs="0" maxOccurs="unbounded"/>
           </xs:sequence>
           <xs:attribute name="seccion" type="xs:string" default="false"/>
          </xs:complexType>
           </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>
-->
<!--EJERCICIO 6-->
  <xs:element name="partidos">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="partido" maxOccurs="3">
          <xs:complexType mixed="true">
            <xs:sequence>
            
              <xs:element name="local" minOccurs="0" maxOccurs="1">
                <xs:complexType mixed="true">
                  <xs:sequence>
                    <xs:element name="goles" type="xs:integer" minOccurs="0" maxOccurs="1"/>
                  </xs:sequence>
                  <xs:attribute name="goles" type="xs:integer" use="optional"/>
                </xs:complexType>
              </xs:element>
              
              <xs:element name="visitante" minOccurs="0" maxOccurs="1">
                <xs:complexType mixed="true">
                  <xs:sequence>
                    <xs:element name="goles" type="xs:integer" minOccurs="0" maxOccurs="1"/>
                  </xs:sequence>
                  <xs:attribute name="goles" type="xs:integer" use="optional"/>
                </xs:complexType>
              </xs:element>
              
            </xs:sequence>
            
            <xs:attribute name="local" type="xs:string" use="optional"/>
            <xs:attribute name="golesLocal" type="xs:integer" use="optional"/>
            <xs:attribute name="visitante" type="xs:string" use="optional"/>
            <xs:attribute name="golesVisitante" type="xs:integer" use="optional"/>
            
          </xs:complexType>
        </xs:element>
        
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== acastineiraduran/LMXI/tri2/Tema4_esquemasXML/boletines/repasoEsquemas.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--a
<articulo codigo="a-1345" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="file:/C:/Users/casty/OneDrive/Escritorio/dam1/lmxi_v2/TEMA%205/boletines/repasoExamen/repasoEsquemas.xsd"></articulo>
-->

<!--b
<empleado xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="file:/C:/Users/casty/OneDrive/Escritorio/dam1/lmxi_v2/TEMA%205/boletines/repasoExamen/repasoEsquemas.xsd">
  <nombre>Marta</nombre>
  <apellidos>
     <apellido1>Perez</apellido1>
    <apellido2>Pérez</apellido2>
   </apellidos>
</empleado>
-->

<!-- c 
<documento xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="file:/C:/Users/casty/OneDrive/Escritorio/dam1/lmxi_v2/TEMA%205/boletines/repasoExamen/repasoEsquemas.xsd">
 Estimado/a <nombre>Pablo Gómez</nombre>.
  Su petición realizada el día:<fecha>2015-03-16</fecha>
  será resuelta el día de hoy a las:<hora>12:10:00</hora>.
</documento>
-->

<!--d
<encargados clase="A1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="file:/C:/Users/casty/OneDrive/Escritorio/dam1/lmxi_v2/TEMA%205/boletines/repasoExamen/repasoEsquemas.xsd">

  <encargado>
      <nombre>Manuel</nombre>
      <apellidos>Pérez</apellidos>
  </encargado>
  <encargado>
      <nombre>Marta</nombre>
      <apellidos>González</apellidos>
  </encargado>

</encargados>
-->
<!--e
<encargados xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="file:/C:/Users/casty/OneDrive/Escritorio/dam1/lmxi_v2/TEMA%205/boletines/repasoExamen/repasoEsquemas.xsd">

  <encargado seccion="s1">
      <nombre>Marta</nombre>
      <apellidos>Sanchez</apellidos>
  </encargado>
  
  <encargado seccion="s2">
      <nombre>Mario</nombre>
      <apellidos>Casillas</apellidos>
  </encargado>

</encargados>
-->
<partidos xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Repaso.xsd">

  <partido>
    <local>Celta
      <goles>2</goles>
    </local>
    <visitante>Depor
      <goles>0</goles>
    </visitante>
  </partido>
  
  <partido>
    <local goles="3">Napoles</local>
    <visitante goles="2">Juventus</visitante>
  </partido>
  
<partido local="Dortmund" golesLocal="5" visitante="Bayern" golesVisitante="3"></partido>  
  
</partidos>
