=== acastineiraduran/LMXI/TEMA 5/tiposDatos.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="datos">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="caracteres" type="xs:string"/>
        <xs:element name="decimal" type="xs:decimal"/>
        <xs:element name="entero" type="xs:integer"/>
        <xs:element name="logico" type="xs:boolean"/>
        <xs:element name="fecha" type="xs:date"/>
        <xs:element name="hora" type="xs:time"/>
        <xs:element name="fechaHora" type="xs:dateTime"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== acastineiraduran/LMXI/TEMA 5/tiposDatos.xml
<?xml version="1.0" encoding="UTF-8"?>

<datos xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="/home/dam1/Angel%20Ejercicios/lmxi_v2/TEMA%205/tiposDatos.xsd">
<caracteres>eedefe</caracteres>
<decimal>4.2</decimal>
<entero>3</entero>
<logico>1</logico><!--tambien podria poner true-->
<fecha>2023-02-13</fecha>
<hora>23:59:59</hora>
<fechaHora>2023-02-05T23:59:59</fechaHora>
</datos>
