=== acastineiraduran/LMXI/TEMA 5/boletines/repasoEsquemas.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
<!--prototipo
  <xs:element name="root">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="element" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>
-->
<!--
  <xs:element name="articulo">
    <xs:complexType>
      <xs:attribute name="codigo" type="xs:string"/>
    </xs:complexType>
  </xs:element>
</xs:schema>
-->
<!--
<xs:element name="empleado">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="nombre" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
        
        <xs:element name="apellidos">
          <xs:complexType>
            <xs:sequence>
            
              <xs:element name="apellido1" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
              <xs:element name="apellido2" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
              
            </xs:sequence>
          </xs:complexType>
         </xs:element>
        
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>
-->
<!--
  <xs:element name="documento">
  <xs:complexType mixed="true">
    <xs:sequence>
    
      <xs:element name="nombre" type="xs:string"/>
      <xs:element name="fecha" type="xs:date"/>
      <xs:element name="hora" type="xs:time"/>
      
    </xs:sequence>
  </xs:complexType>
</xs:element>
</xs:schema>
-->
  <xs:element name="encargados">
    <xs:complexType>
        <xs:sequence>
        
          <xs:element name="encargado" minOccurs="0" maxOccurs="unbounded">
            <xs:complexType>
              <xs:sequence>
              
              <xs:element name="nombre" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
              <xs:element name="apellidos" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
              
              </xs:sequence>
            </xs:complexType>
          </xs:element>
              
              
        </xs:sequence>
      <xs:attribute name="clase" type="xs:string"/>
    </xs:complexType>
  </xs:element>
  
</xs:schema>

=== acastineiraduran/LMXI/TEMA 5/boletines/repasoEsquemas.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
<articulo codigo="a-1345" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="/home/dam1/Angel%20Ejercicios/lmxi_v2/TEMA%205/boletines/repasoEsquemas.xsd"></articulo>
-->
<!--
<empleado xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="/home/dam1/Angel%20Ejercicios/lmxi_v2/TEMA%205/boletines/repasoEsquemas.xsd"> 
  <nombre>Marta</nombre>
  <apellidos>
     <apellido1>Pérez</apellido1>
      <apellido2>Pérez</apellido2>
  </apellidos>
</empleado>
-->
<!--
<documento xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="/home/dam1/Angel%20Ejercicios/lmxi_v2/TEMA%205/boletines/repasoEsquemas.xsd">
 Estimado/a <nombre>Pablo Gómez</nombre>.
  Su petición realizada el día:<fecha>2015-03-16</fecha>
  será resuelta el día de hoy a las:<hora>12:10:00</hora>.
</documento>
-->
<!--
<encargados clase="A1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="/home/dam1/Angel%20Ejercicios/lmxi_v2/TEMA%205/boletines/repasoEsquemas.xsd">
  
  <encargado>
    <nombre>Manuel</nombre>
    <apellidos>Pérez</apellidos>
  </encargado>
  
  <encargado>
    <nombre>Marta</nombre>
    <apellidos>González</apellidos>
  </encargado>
  
</encargados>
-->
<encargados> 
    <encargado seccion=”s1”>
    <nombre>Marta</nombre>
    <apellidos>Sanchez</apellidos>
    <encargado>
 <encargado seccion=”s2”>
  <nombre>Mario</nombre>
  <apellidos>Casillas</apellidos>
<encargado>
</encargados>
